# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    groups:
      gha-major:
        patterns:
          - "*"
        update-types:
          - "major"
      gha-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      gha-unknown:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    groups:
      npm-production-major:
        dependency-type: "production"
        update-types:
          - "major"
      npm-production-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-production-unknown:
        dependency-type: "production"
      npm-development-major:
        dependency-type: "development"
        update-types:
          - "major"
      npm-development-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      npm-development-unknown:
        dependency-type: "development"
