name: "[PR] Validate"
on:
  pull_request:
    branches:
      - "*"
jobs:
  run-pr-validation:
    name: Validate PR
    uses: navikt/crm-workflows-base/.github/workflows/validate.yml@master
    permissions:
      contents: read
    secrets: inherit